version: '3.1'
services:
  web:
    build: .
    ports:
     - "8082:8082"
    expose:
      - "8082"
    links:
      - sor
#      - db
    environment:
      SOR_HOST: sor
      SOR_PORT: 8081

  db:
    image: tutum/mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASS: mysql
      ON_CREATE_DB: imagesor
    ports:
      - "3306:3306"
    expose:
        - "3306"

  sor:
    image: sor_web
    ports:
      - "8081:8081"
    expose:
      - "8081"
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: mysql
      DB_DATABASE: imagesor