version: '3.1'
services:
  web:
    build: .
    ports:
     - "8082:8082"
    expose:
      - "8082"
    links:
      - sor
      - db2
    environment:
      SOR_HOST: sor
      SOR_PORT: 8081
      DB_HOST: db2
      DB_PORT: 3307
      DB_USER: mysql
      DB_PASS: mysql
      DB_DATABASE: imagesod

  db2:
    image: tutum/mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASS: mysql
      ON_CREATE_DB: imagesod
    expose:
      - "3307"

  db1:
    image: tutum/mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASS: mysql
      ON_CREATE_DB: imagesor
    expose:
        - "3306"

  sor:
    image: sor_web
    ports:
      - "8081:8081"
    expose:
      - "8081"
    links:
      - db1
    environment:
      DB_HOST: db1
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: mysql
      DB_DATABASE: imagesor