spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imagesod?useSSL=false
    username: mysql
    password: mysql

  jpa:
    show-sql: true

# to see transaction detail, should be info in prod
logging.level.org.springframework.transaction.interceptor: TRACE