version: '3.1'
services:
  nginx:
    image: nginx:1.13.12
    ports:
      - "8080:80"
    restart: always
    links:
      - sod
      - sor
    volumes:
      - ./conf.d:/etc/nginx/conf.d
#      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx

  sod:
    image: sod_web
    expose:
      - "8082"
    links:
      - sor
      - sod_db
    environment:
      SOR_HOST: sor
      SOR_PORT: 8081
      DB_HOST: sod_db
      DB_PORT: 3306
      DB_USER: mysql
      DB_PASS: mysql
      DB_DATABASE: imagesod

  sod_db:
    image: tutum/mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASS: mysql
      ON_CREATE_DB: imagesod
    expose:
      - "3306"

  sor_db:
    image: tutum/mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASS: mysql
      ON_CREATE_DB: imagesor
    expose:
        - "3306"

  sor:
    image: sor_web
    expose:
      - "8081"
    links:
      - sor_db
    environment:
      DB_HOST: sor_db
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: mysql
      DB_DATABASE: imagesor